config/routes.rb
Rails.application.routes.draw do
  root 'rooms#top'
  # users
  get 'users/account', to: 'users#account'
  get 'users/profile', to:  'users#profile'
  get 'users/profile/edit', to: 'users#edit_profile'
  patch 'users/profile/edit', to: 'users#update_profile'
  # rooms
  get 'rooms/own', to: 'rooms#own'
  get 'rooms/search', to: 'rooms#search'
  get 'rooms/top', to: 'rooms#top'
  #reservations
  get 'reservations/index', to: "reservations#index"
  post 'reservations/confirm', to: 'reservations#confirm'
  post 'reservations/create', to: 'reservations#create'
  
  devise_for :users, controllers: {
    registrations:  'users/registrations'
  }
  resources :rooms, except: [:edit, :update, :destroy, :index]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :image
  has_many :rooms
  has_many :reservations

  validates :name, presence: true
  validates :intro, length: { maximum: 150 }

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  
  # 編集後の遷移先
  protected 
    def after_update_path_for(resource)
      rooms_top_path
    end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def account
    @user = current_user
  end
  
  def profile
    @user = current_user
  end

  def edit_profile 
    @user = current_user
  end

  def update_profile
    @user = current_user
    if @user.update(user_params)
      flash[:ok] = '更新しました'
      redirect_to users_profile_path
    else 
      flash.now[:alert] = '更新できませんでした'
      render :edit_profile
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :intro, :image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/account.erb
<h2>設定</h2>
<div class='acount-profile-button-container'>
    <%= link_to "アカウント", users_account_path, class: "btn btn-primary"  %>
    <%= link_to "プロフィール", users_profile_path, class: "btn btn-primary" %>
</div>
<div class= 'account-container'>
    <h4>メールアドレス</h4>
    <p><%= @user.email %></p>
    <h4>パスワード</h4>
    <p>*******</p>
    <div class='edit-button-container'>
    <%= link_to '編集', edit_user_registration_path, class: "btn btn-outline-primary" %>
</div>
</div>

app/views/users/edit_profile.html.erb
<h3>プロフィール編集</h3>
<div class="profile-edit-container">
    <%= form_with model: @user, url: users_profile_edit_path do |f| %>
    <table>
        
        <tr>
            <th><%= f.label :image, '画像' %></th>
            <td><%= f.file_field :image %></td>
        </tr>
        <tr>
            <th><%= f.label :name, '名前' %></th>
            <td><%= f.text_field :name %></td>
        </tr>
      
        <tr>
            <th><%= f.label :intro, '自己紹介' %></th>
            <td><%= f.text_field :intro %></td>
        </tr>
    </table>
    <%= f.submit '登録する', class: "btn btn-primary" %>
<% end %>
<%= link_to "キャンセル", users_profile_path  %>

</div>

<% if flash.now[:alert] %>
    <p><%= flash.now[:alert] %></p>
<% end %>

app/views/users/profile.html.erb
<% if flash[:ok] %>
    <p class="notice"><%= flash[:ok] %></p>
<% end %>

<h2>設定</h2>
<%= link_to "アカウント", users_account_path, class: "btn btn-primary" %>
<%= link_to "プロフィール", users_profile_path, class: "btn btn-primary" %>

<div class="profile-container">
    <% if current_user.image.attached? %>
    <%= image_tag @user.image, class: "rounded-circle", width: "100px"%>
    <% else %>
    <%= image_tag 'default-avatar.png', class: "rounded-circle", width: "100px"%>
    <% end %>
    <p><%= @user.name %></p>
    <h4>自己紹介</h4>
    <p><%= @user.intro %></p>
    <div class="profile-button-container">
        <%= link_to '編集', users_profile_edit_path, class: "btn btn-outline-primary" %> 
    </div>
   
</div>

app/views/users/show.html.erb
<h2>設定</h2>

<h3>アカウント</h3>
<%= link_to '編集', edit_user_registration_path %>
<div>
    <h4>メールアドレス</h4>
    <p><%= @user.email %></p>
    <h4>パスワード</h4>
    <p>*******</p>

</div>