config/routes.rb
Rails.application.routes.draw do
  root 'rooms#top'
  # users
  get 'users/account', to: 'users#account'
  get 'users/profile', to:  'users#profile'
  get 'users/profile/edit', to: 'users#edit_profile'
  patch 'users/profile/edit', to: 'users#update_profile'
  # rooms
  get 'rooms/own', to: 'rooms#own'
  get 'rooms/search', to: 'rooms#search'
  get 'rooms/top', to: 'rooms#top'
  #reservations
  get 'reservations/index', to: "reservations#index"
  post 'reservations/confirm', to: 'reservations#confirm'
  post 'reservations/create', to: 'reservations#create'
  
  devise_for :users, controllers: {
    registrations:  'users/registrations'
  }
  resources :rooms, except: [:edit, :update, :destroy, :index]
end

app/models/reservation.rb
class Reservation < ApplicationRecord
    belongs_to :room
    belongs_to :user

    validates :checkin, presence: {message: "チェックインが入力されていません"}, on: :before_confirm
    validates :checkout, presence: {message: "チェックアウトが入力されていません"}, on: :before_confirm
    validates :count_ppl, presence: {message: "人数が入力されていません"}, numericality: {only_integer: true, greater_than_or_equal_to: 1, message: '人数は1人以上にしてください'}, on: :before_confirm
    validate :in_out_check, on: :before_confirm
    def in_out_check
        unless checkout.nil? || checkin.nil?
            if checkout  < checkin
                errors.add :base, message: 'チェックアウトはチェックイン以降の日付にしてください'
            end
        end
        if checkin && checkin < Date.today
            errors.add(:checkin, 'チェックインは今日以降の日付を入力してください')
        end
        if checkout && checkout < Date.today
            errors.add(:checkout, 'チェックアウトは今日以降の日付を入力してください')
        end
    end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  
  def index
    @reservations = current_user.reservations.includes(:room)
  end

  def create
    @reservation = Reservation.new(create_params)
    if @reservation.save
      redirect_to reservations_index_path
    else
      render :confirm
    end
  end

  def confirm
    @reservation = Reservation.new(confirm_params)
    @room_id = @reservation.room_id
    @room = Room.find(@room_id)

    if @reservation.validate(:before_confirm)
      @days = (@reservation.checkout - @reservation.checkin).to_i 
      @total_fee = @room.fee * @reservation.count_ppl * @days  
    else
      flash.now[:reservation_error] = @reservation.errors.full_messages.join(" ")
      render "rooms/show"
    end    
  end

  private
  def create_params
    params.require(:reservation).permit(:checkin, :checkout, :count_ppl, :user_id, :room_id, :payment)
  end

  def confirm_params
    params.require(:reservation).permit(:checkin, :checkout, :count_ppl, :user_id, :room_id)
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/confirm.html.erb
<div>
    <h3>予約内容の確認</h3>
    <table>
        <tr>
            <th>チェックイン</th>
            <td><%= @reservation.checkin %></td>
        </tr>
        <tr>
            <th>チェックアウト</th>
            <td><%= @reservation.checkout %></td>
        </tr>
        <tr>
            <th>日数</th>
            <td><%= "#{@days}日" %></td>
        </tr>
        <tr>
            <th>人数</th>
            <td><%= "#{@reservation.count_ppl}人"%></td>
        </tr>
        <tr>
            <th>お支払い金額</th>
            <td><%= "¥#{@total_fee}" %></td>
        </tr>
    </table>
    <p>上記で正しければ確定ボタンを押してください。</p>
    <%= form_with model: @reservation, url: {controller: 'reservations', action: 'create' } do |f| %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.hidden_field :checkin, value: @reservation.checkin %>
    <%= f.hidden_field :checkout, value: @reservation.checkout %>
    <%= f.hidden_field :payment, value: @total_fee %>
    <%= f.hidden_field :room_id, value: @reservation.room_id %>
    <%= f.submit class: "btn btn-primary" %>
    <% end %>
    <%= link_to "キャンセル", room_path(@room.id) %>
</div>

app/views/reservations/index.html.erb
<div>
    <h3>予約済み一覧</h3>
    <table>
        <tr>
            <th>画像</th>
            <th>施設名</th>
            <th>紹介文</th>
            <th>合計料金</th>
            <th>チェックイン</th>
            <th>チェックアウト</th>
            <th>予約確定日時</th>
        </tr>

        <% @reservations.each do |r| %>
            <tr>
                <td><%= render partial: "shared/image_common", locals: {obj: r.room, width: '150px'} %></td>
                <%= render partial: "shared/room_index_common", locals: { obj: r.room, payment: r.payment} %>
                <td><%= r.checkin %></td>
                <td><%= r.checkout %></td>
                <td><%= r.created_at.strftime("%Y/%m/%d %H:%M") %></td>
            </tr>
            <% end %>
    </table>
</div>