config/routes.rb
Rails.application.routes.draw do
  root 'rooms#top'
  # users
  get 'users/account', to: 'users#account'
  get 'users/profile', to:  'users#profile'
  get 'users/profile/edit', to: 'users#edit_profile'
  patch 'users/profile/edit', to: 'users#update_profile'
  # rooms
  get 'rooms/own', to: 'rooms#own'
  get 'rooms/search', to: 'rooms#search'
  get 'rooms/top', to: 'rooms#top'
  #reservations
  get 'reservations/index', to: "reservations#index"
  post 'reservations/confirm', to: 'reservations#confirm'
  post 'reservations/create', to: 'reservations#create'
  
  devise_for :users, controllers: {
    registrations:  'users/registrations'
  }
  resources :rooms, except: [:edit, :update, :destroy, :index]
end

app/models/room.rb
class Room < ApplicationRecord
    belongs_to :user
    has_many :reservations
    has_one_attached :image

    validates :name, presence: true
    validates :intro, presence: true
    validates :address, presence: true
    validates :fee, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}

    #ransack 設定
    def self.ransackable_attributes(auth_object = nil)
        ["address", "name", "intro"]
    end
    def self.ransackable_associations(auth_object = nil)
        []
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_q, only: [:index, :top, :search]
  def own
    @rooms = Room.where(user_id: current_user.id)
  end

  def top

  end

  def show
    @room = Room.find(params[:id])
    @reservation = Reservation.new
    @user = current_user
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(create_params)
    if @room.save
      flash[:room_notice] = '施設の新規登録をしました'
      redirect_to room_path(@room)
    else
      flash.now[:room_alert] = '施設を登録できませんでした'
      render :new
    end
  end

  def search
    @results = @q.result
    @sum_rooms = @results.count
  end

  private
  def set_q
    @q = Room.ransack(params[:q])
  end
  
  def create_params
    params.require(:room).permit(:name, :intro, :fee, :address, :image, :user_id)
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/new.html.erb
<h3>新規登録</h3>

<%= form_with model: @room do |f| %>
    <table>
        <tr>
            <th><%= f.label :name, "施設名＊" %></th>
            <td><%= f.text_field :name %></td>
        </tr>
        <tr>
            <th><%= f.label :intro, "施設詳細＊" %></th>
            <td><%= f.text_area :intro %></td>
        </tr>
        <tr>
            <th><%= f.label :fee, "料金＊" %></th>
            <td><%= f.number_field :fee %></td>
        </tr>
        <tr>
            <th><%= f.label :address, "住所＊" %></th>
            <td><%= f.text_area :address %></td>
        </tr>
        <tr>
            <%= f.file_field :image %>
        </tr>  
    </table>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <p><%= f.submit "投稿を完了する", class: "btn btn-primary" %></p>
    <% end %>
    
    <% if flash[:room_alert] %>
        <p class="notice"><%= flash[:room_alert] %></p>
    <% end %>


 

app/views/rooms/own.html.erb
<div>
    <table>
        <tr>
            <th>施設画像</th>
            <th>施設名</th>
            <th>紹介文</th>
            <th>料金</th>
            <th>作成日</th>
        </tr>
        <% @rooms.each do |room| %>
        <tr>
            <td><%= render partial: 'shared/image_common', locals: { obj: room, width: '150px'} %></td>
            <%= render partial: 'shared/room_index_common', locals: { obj: room, payment: room.fee} %>
            <td><%= room.created_at.strftime("%Y/%m/%d") %></td>
        </tr>
        <% end %>
    </table>
</div>

app/views/rooms/search.html.erb
<h3><%= "検索結果 #{@sum_rooms}件" %></h3>

<div class="search-page-container">
    <%= search_form_for @q, url: rooms_search_path do |f| %>
    <%= f.search_field :address_cont, placeholder: 'エリアを入力' %>
    <%= f.submit '検索', class:"btn btn-outline-primary"%>
    <% end %>
    <%= search_form_for @q, url: rooms_search_path do |f| %>
    <%= f.search_field :name_or_intro_cont, placeholder: 'キーワードを入力' %>
    <%= f.submit '検索', class:'btn btn-outline-primary' %>
    <% end %>
</div>
<div class="rooms-index-container">
    
        <% @results.each do |room| %>
        <ul class="rooms-index-ul">
            <li><%= render partial: "shared/image_common", locals: { obj: room, width: '80%'} %></li>
            <%= render partial: "shared/room_common", locals: { obj: room} %>
            <%= link_to '詳細', room_path(room), class: 'btn btn-primary' %>
        </ul>
        <% end %>
    
</div>

app/views/rooms/show.html.erb
<div class="room-show-container">
    <%=  link_to '戻る', :back, class: "btn btn-outline-primary"%>
    <div class="room-show-contents-container">
        <ul class="room-show-ul">
            <li><%= render partial: 'shared/image_common', locals: {obj: @room, width: '500px'} %></li>
                <%= render partial: "shared/room_common", locals: { obj: @room} %>
            </ul> 
        
            <% if flash[:room_notice] %>
            <p class="notice"><%= flash[:room_notice] %></p>
            <% end %>
        
        <!-- 予約フォーム -->
        <% if user_signed_in? %>
            <%= form_with model: @reservation, url: reservations_confirm_path, method: :post do |f| %>
                <table>
                    <tr>
                        <th><%= f.label :checkin, "チェックイン" %></th>
                        <th><%= f.label :checkout, "チェックアウト" %></th>
                        <th><%= f.label :count_ppl, '人数' %></th>
                    </tr>
                    <tr>
                        <td><%= f.date_field :checkin %></td>
                        <td><%= f.date_field :checkout %></td>
                        <td><%= f.number_field :count_ppl%></td>
                    </tr>
                </table>
                <%= f.hidden_field :user_id, value: current_user.id %>
                <%= f.hidden_field :room_id, value: @room.id %>
                <p><%= f.submit class: "btn btn-primary" %></p>
            <% end %>
            
            <% if flash.now[:reservation_error] %>
            <p class="notice"><%= flash.now[:reservation_error] %></p>
            <% end %>
        <% else %>
            <p>〜ログインしてホテルを予約しましょう！〜</p>
        <% end %>
    </div>
    
</div>

app/views/rooms/top.html.erb
<div class='room-top-container'>
    <div class="search-photo-container">
        <div class="top-photo-container">
            <%= image_tag('forest.jpg', width: '100%')  %>
        </div> 
        <div class="top-search-container">
            <p class="top-p">Potepan Shareでまだ体験したことのない旅をしよう</p>
            <%= search_form_for @q, url: rooms_search_path do |f| %>
            <%= f.search_field :address_cont, placeholder: 'エリアを入力', class: "form-control" %>
            <p><%= f.submit '検索', class: "btn btn-primary"%></p>
            <% end %>
        </div>
    </div>
    
    <div class="top-area">
        <h2 class="top-area-h2">おすすめのエリア</h2>
        <%= link_to image_tag('tokyo.jpg', width:  '500px'), rooms_search_path(q: {address_cont: '東京都'}) %>
        <p>東京</p>
        <%= link_to image_tag('osaka.jpg', width:  '500px'), rooms_search_path(q: {address_cont: '大阪府'}) %>
        <p>大阪</p>
        <%= link_to image_tag('kyoto.jpg', width:  '500px'), rooms_search_path(q: {address_cont: '京都府'}) %>
        <p>京都</p>
        <%= link_to image_tag('sapporo.jpg', width:  '500px'), rooms_search_path(q: {address_cont: '札幌'}) %>
        <p>札幌</p>
    </div>
</div>